### ISSUE TITLE
Unable to Run the application

### ISSUE THREAD

**Issue by krish07** [rajagopal28/Donna#1]
Hi Raja,
I have downloaded this code base and whe I run the application using ng serve
It is showing like
 **ERROR in D:/Angular2/indoor/Donna-master/src/app/chat-bot/chat-bot.component.ts
(62,42): Argument of type '{ contexts: [any]; }' is not assignable to parameter
of type 'IRequestOptions'.
  Object literal may only specify known properties, and 'contexts' does not exis
t in type 'IRequestOptions'.** Please advice

**Comment by rajagopal28** [comment]
Hi,
 This is a work in progress application so few things are broken right now. May I know why you are trying to run my application? If you tell me what you are trying to achieve I may point you in right direction.

**Comment by krish07** [comment]
I just want to see the indoor navigation how it works as you shown in the images. I like this concept.

**Comment by rajagopal28** [comment]
Hi,
  If you are only intending to view then you can view the last stable build at this link.  [Live](https://rajagopal28.github.io/Donna/#/indoor-map). I have used the native javascript library provided by MazeMap and I was not able to wrap it with angular2. Following are some of the links for your reference to try it on your own:
https://blog.mazemap.com/introducing-mazemap-indoor-map-javascript-api-v1-0/
https://www.mazemap.com/indoor-maps
https://api.mazemap.com/js/v1.2.10/docs/examples.html

I do not have time to fix this right now. I'll try to get this done over this weekend.

**Comment by rajagopal28** [comment]
Fixing the local setup issue. You need your own API keys for maps and chat.
